package br.com.alura.jdbc;

import java.sql.Connection;
import java.sql.SQLException;

import javax.sql.DataSource;

import org.hsqldb.jdbc.JDBCPool;

/**
 * http://www.mauda.com.br/?p=495
 * 
 * create table category (id integer generated by default as identity primary key, name varchar(255));
 * create table product (id integer generated by default as identity primary key, name varchar(255), description varchar(255), category_id integer);
 */

public class ConnectionPool {
	
	private DataSource dataSource;

	public ConnectionPool() {
        JDBCPool pool = new JDBCPool();
        pool.setUrl("jdbc:hsqldb:hsql://localhost/myServerDB");
        pool.setUser("SA");
        pool.setPassword("");
        this.dataSource = pool;
    }

    public Connection getConnection() throws SQLException {
        return dataSource.getConnection();
    }
}
