package br.com.alura.jdbc;

import java.sql.Connection;
import java.sql.SQLException;
import javax.sql.DataSource;
import org.apache.commons.dbcp.BasicDataSource;

/**
 * http://www.mauda.com.br/?p=495
 *
 * create table category (id integer generated by default as identity primary key, name varchar(255));
 * create table product (id integer generated by default as identity primary key, name varchar(255), description
 * varchar(255), category_id integer);
 */

public class ConnectionPool {

    private DataSource dataSource;

    ConnectionPool() {
        BasicDataSource basicDataSource = new BasicDataSource();
        basicDataSource.setDriverClassName("com.mysql.cj.jdbc.Driver");
        basicDataSource.setUrl("jdbc:mysql://localhost:3306/storeDB?createDatabaseIfNotExist=true&useSSL=false");
        basicDataSource.setUsername("root");
        basicDataSource.setPassword("root");
        basicDataSource.setInitialSize(1);
        this.dataSource = basicDataSource;
    }

    public Connection getConnection() throws SQLException {
        return dataSource.getConnection();
    }
}
